[package]

name = "skiplist"
version = "0.2.8"
authors = ["JP-Ellis <coujellis@gmail.com>"]

description = "Skiplist implementation in rust, providing fast insertion and removal.  A normal skiplist is implemented, as well as an ordered skiplist and a skipmap."

documentation = "https://jp-ellis.github.io/rust-skiplist/skiplist/"
homepage = "https://www.github.com/JP-Ellis/rust-skiplist/"
repository = "https://www.github.com/JP-Ellis/rust-skiplist/"

readme = "README.md"

keywords = ["collection", "skiplist", "sorted"]

license = "MIT"

[dependencies]

rand = "*"
